### ISSUE TITLE
Addestramento `SimpleAutoencoder`

### ISSUE THREAD

**Issue by peiva-git** [peiva-git/deep_learning_project#42]
Eseguire addestramento del `SimpleAutoencoder` tramite notebook, verificando eventuali problemi.

Addestrare intanto su MNIST e CIFAR10.

**Comment by FedericoCalandra** [comment]
Attualmente il notebook simple_model.ipynb addestra i due SimpleAutoencoder (uno usando il dataset MNIST e l'altro usando CIFAR10). C'è solo un bug relativo al salvataggio dei parametri del modello (FileNotFoundError: [Errno 2] No such file or directory: 'output/models/simple_autoencoder_mnist.keras') che dovrei risolvere in giornata

**Comment by peiva-git** [comment]
Puoi dare un'occhiata alla soluzione in #45. L'errore appare perché non c'è la struttura di cartelle specificata.
