### ISSUE TITLE
model attribute in SimpleAutoencoder should be public

### ISSUE THREAD

**Issue by FedericoCalandra** [peiva-git/deep_learning_project#47]
Altrimenti non è possibile usare il modello dopo averlo salvato

**Comment by peiva-git** [comment]
Non funziona con `simple_autoencoder.model = tf.keras.saving.load_model('filepath')`?

**Comment by FedericoCalandra** [comment]
Sì funziona! Devo sistemare un po' il codice. Non occorre modificare l'attributo model
