### ISSUE TITLE
New RENOIR dataset

### ISSUE THREAD

**Issue by FedericoCalandra** [peiva-git/deep_learning_project#63]
**Is your feature request related to a problem? Please describe.**
Il dataset RENOIR è troppo grande per essere utilizzato con l'architettura Restormer.

**Describe the solution you'd like**
Partizionare il dataset in un insieme di N patch per ogni immagine. Valutare se mantenere solo qualche patch per ogni immagine. Inserire un metodo che salvi in locale il nuovo dataset.

**Describe alternatives you've considered**
Altrenativamente sarebbe possibile ridimensionare le immagini. In tal caso però ho paura che perderemmo parte dell'informazione associata al rumore reale. Se ricaviamo dei patch possiamo preservare il rumore ricavato in fase di acquisizione delle immagini.

**Comment by peiva-git** [comment]
Hai provato a visualizzare come sembra l'immagine ridimensionata? Secondo me il risultato dovrebbe essere accettabile. Vedi anche commento in #64.
